######################
# Spring Configuration
#####################
spring:
  application:
    name: Patient Demographics API
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_demographics
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#####################
# Actuator Configuration
#####################
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httpexchanges
#####################
# Server Configuration
#####################
server:
  port: 8081