spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_demographics
    username: postgres
    password: zkfmtmak
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update